language: java
jdk: openjdk13
script:
  - mvn clean package -B
  - docker build -t perdian/flightlog .
sudo: required
services:
  - docker
notifications:
  email: 
    on_success: change
    on_failure: always
