spring:
  datasource:
    url: jdbc:h2:~/Development/databases/flighttrackerdb
    username: sa
    password:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 5MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  
security:
  enable-csrf: true
  
server:
  jsp-servlet:
    init-parameters:
      development: true
      trimSpaces: true

flyway:
  encoding: UTF-8
  locations:
  - "classpath:de/perdian/apps/flighttracker/flyway/"
  validate-on-migrate: false
