spring:
  datasource:
    url: ${FLIGHTLOG_DB_URL:jdbc:h2:/var/flightlog/database/flightlog}
    driver-class-name: ${FLIGHTLOG_DB_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${FLIGHTLOG_DB_USERNAME:sa}
    password: ${FLIGHTLOG_DB_PASSWORD:}
  jpa:
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${FLIGHTLOG_AUTHENTICATION_OAUTH2_GOOGLE_CLIENT_ID:null}
            client-secret: ${FLIGHTLOG_AUTHENTICATION_OAUTH2_GOOGLE_CLIENT_SECRET:null}
  servlet:
    multipart:
      max-file-size: 10MB
  thymeleaf:
    cache: false

server:
  port: ${FLIGHTLOG_SERVER_PORT:8080}
  error:
    whitelabel:
      enabled: true
  servlet:
    contextPath: ${FLIGHTLOG_SERVER_CONTEXT_PATH:/flightlog}
    session:
      cookie:
        name: ${FLIGHTLOG_SERVER_COOKIE_NAME:flightlog-session}
    encoding:
      charset: UTF-8
      enabled: true
      force: true

flightlog:
  authentication:
    required: ${FLIGHTLOG_AUTHENTICATION_REQUIRED:false}
    oauth:
      enabled: ${FLIGHTLOG_AUTHENTICATION_OAUTH2_ENABLED:false}
    local:
      enabled: ${FLIGHTLOG_AUTHENTICATION_LOCAL_ENABLED:true}
  registration:
    restricted: ${FLIGHTLOG_AUTHENTICATION_REGISTRATION_RESTRICTED:true}
    email-whitelist: ${FLIGHTLOG_AUTHENTICATION_REGISTRATION_EMAIL_WHITELIST:}
  backup:
    cron: ${FLIGHTLOG_BACKUP_CRON:}
    target: ${FLIGHTLOG_BACKUP_TARGET:}
