spring:
  datasource:
    url: ${FLIGHTLOG_DB_URL:jdbc:h2:${FLIGHTLOG_DB_DIRECTORY:~/.flightlog/}/flightlogdb}
    driver-class-name: ${FLIGHTLOG_DB_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${FLIGHTLOG_DB_USERNAME:sa}
    password: ${FLIGHTLOG_DB_PASSWORD:}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
  thymeleaf:
    cache: false
  threads:
    virtual:
      enabled: true

server:
  port: ${FLIGHTLOG_SERVER_PORT:8080}
  error:
    whitelabel:
      enabled: false
  servlet:
    contextPath: ${FLIGHTLOG_SERVER_CONTEXT_PATH:/flightlog}
    session:
      cookie:
        name: ${FLIGHTLOG_SERVER_COOKIE_NAME:flightlog-session}
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  compression:
    enabled: true

flightlog:
  registration:
    emailAddressesAllowlist: ${FLIGHTLOG_REGISTRATION_EMAIL_ADDRESSES_ALLOWLIST:}
    allowByDefault: ${FLIGHTLOG_REGISTRATION_ALLOW_BY_DEFAULT:false}
  backup:
    cron: ${FLIGHTLOG_BACKUP_CRON:}
    onlyForNewContent: ${FLIGHTLOG_BACKUP_ONLYFORNEWCONTENT:true}
    filesystem:
      directory: ${FLIGHTLOG_BACKUP_FILESYSTEM_DIRECTORY:}
