version: 2.1

executors:
  docker:
    docker:
      - image: circleci/openjdk:13-buster

jobs:
  build:
    executor: docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: "Build using Maven"
          command: |
            mvn -B clean package
      - save_cache:
          paths: ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}      
      - store_test_results:
          path: target/surefire-reports
      - persist_to_workspace:
          root: target/
          paths: "*.war"
  publish:
    executor: docker
    steps:
      - checkout
      - attach_workspace:
          at: target/
      - setup_remote_docker
      - run:
          name: "Build Docker image"
          command: |
            docker build -t perdian/flightlog .
            echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          requires: [ "build" ]
##      - publish:
##          filters:
##            branches:
##              ignore: /.*/
##            tags:
##              only: /release-.*/                
