spring:
  datasource:
    url: ${FLIGHTLOG_DB_URL:jdbc:h2:/var/flightlog/database/flightlog}
    driver-class-name: ${FLIGHTLOG_DB_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${FLIGHTLOG_DB_USERNAME:sa}
    password: ${FLIGHTLOG_DB_PASSWORD:}
  flyway:
    encoding: UTF-8
    locations:
      - "classpath:de/perdian/flightlog/flyway/"
    validate-on-migrate: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: ${FLIGHTLOG_DB_HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${FLIGHTLOG_AUTHENTICATION_OAUTH2_GOOGLE_CLIENT_ID:null}
            client-secret: ${FLIGHTLOG_AUTHENTICATION_OAUTH2_GOOGLE_CLIENT_SECRET:null}
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: ${FLIGHTLOG_SERVER_PORT:8080}
  error:
    whitelabel:
      enabled: false
  servlet:
    contextPath: ${FLIGHTLOG_SERVER_CONTEXT_PATH:/flightlog}
    jsp:
      init-parameters:
        development: ${FLIGHTLOG_SERVLET_DEVELOPMENT_MODE:false}
        trimSpaces: true
    session:
      cookie:
        name: ${FLIGHTLOG_SERVER_COOKIE_NAME:flightlog-session}
    encoding:
      charset: UTF-8
      enabled: true
      force: true

flightlog:
  authentication:
    required: ${FLIGHTLOG_AUTHENTICATION_REQUIRED:false}
    ldap:
      enabled: ${FLIGHTLOG_AUTHENTICATION_LDAP_ENABLED:false}
      url: ${FLIGHTLOG_AUTHENTICATION_LDAP_URL}
      base-dn: ${FLIGHTLOG_AUTHENTICATION_LDAP_BASE_DN}
      user-dn: ${FLIGHTLOG_AUTHENTICATION_LDAP_USER_DN:ou=users}
      bind-dn: ${FLIGHTLOG_AUTHENTICATION_LDAP_BIND_DN}
      bind-password: ${FLIGHTLOG_AUTHENTICATION_LDAP_BIND_PASSWORD}
      username-field: ${FLIGHTLOG_AUTHENTICATION_LDAP_USERNAME_FIELD:uid}
    oauth:
      enabled: ${FLIGHTLOG_AUTHENTICATION_OAUTH2_ENABLED:false}
    local:
      enabled: ${FLIGHTLOG_AUTHENTICATION_LOCAL_ENABLED:true}
  registration:
    restricted: ${FLIGHTLOG_AUTHENTICATION_REGISTRATION_RESTRICTED:true}
    email-whitelist: ${FLIGHTLOG_AUTHENTICATION_REGISTRATION_EMAIL_WHITELIST:}
  backup:
    cron: ${FLIGHTLOG_BACKUP_CRON:}
    target: ${FLIGHTLOG_BACKUP_TARGET:}